In [31]:
import numpy as np
import os

In [32]:
diff_dir = dataset = '/home/drevital/obstacles_classification_datasets/may22_b_1_5__1_0/eval/diffs'
tf_names = ['tf1.npz', 'tf2.npz', 'tf3.npz']
trt_names = ['trt1.npz', 'trt2.npz', 'trt3.npz']

In [33]:
tf = []
trt = []

for i in range(3):
    tf.append(np.load(os.path.join(diff_dir, tf_names[i])))
    trt.append(np.load(os.path.join(diff_dir, trt_names[i])))    

In [36]:
data = tf[0]
data['tf1'][0][:5]

array([[0.31764707, 0.34901962, 0.28235295],
       [0.31764707, 0.34901962, 0.28235295],
       [0.31764707, 0.34901962, 0.28235295],
       [0.31764707, 0.34901962, 0.28235295],
       [0.31764707, 0.34901962, 0.28235295]], dtype=float32)

In [40]:
tf[0]['tf1'].shape

(200, 200, 3)

In [42]:
trt1 = np.array(trt[0]['trt1']).reshape((200, 200, 3))

In [44]:
trt1[0][:5]

array([[0.317647, 0.34902 , 0.282353],
       [0.317647, 0.34902 , 0.282353],
       [0.317647, 0.34902 , 0.282353],
       [0.317647, 0.34902 , 0.282353],
       [0.317647, 0.34902 , 0.282353]], dtype=float32)

In [50]:
tf1 = np.array(tf[0]['tf1'])

In [54]:
tf1.dtype, trt1.dtype

(dtype('float32'), dtype('float32'))

In [56]:
s1 = np.sum(tf1)

In [57]:
s2 = np.sum(trt1)

In [58]:
s1, s2

(28390.59, 28384.209)

In [61]:
tf2 = np.array(tf[1]['tf2'])

In [62]:
trt2 = np.array(trt[1]['trt2']).reshape((200, 200, 3))

In [64]:
tf2[0][:5]

array([[0.34901962, 0.3803922 , 0.3372549 ],
       [0.34901962, 0.3803922 , 0.3372549 ],
       [0.34901962, 0.3803922 , 0.3372549 ],
       [0.34901962, 0.3803922 , 0.3372549 ],
       [0.34901962, 0.3803922 , 0.3372549 ]], dtype=float32)

In [66]:
trt2[0][:5]

array([[0.34902 , 0.384314, 0.333333],
       [0.34902 , 0.384314, 0.333333],
       [0.34902 , 0.384314, 0.333333],
       [0.34902 , 0.384314, 0.333333],
       [0.34902 , 0.384314, 0.333333]], dtype=float32)

In [67]:
tf3 = np.array(tf[2]['tf3'])

In [69]:
trt3 = np.array(trt[2]['trt3']).reshape((200, 200, 1))

In [73]:
tf3[0][:50]

array([0.9972079, 0.9972079, 0.9972079, 0.9972079, 0.9972079, 0.9972079,
       0.9972079, 0.9972079, 0.9972079, 0.9972079, 0.9972079, 0.9972079,
       0.9960785, 0.9960785, 0.9960785, 0.9960785, 0.9960785, 0.9960785,
       1.       , 1.       , 1.       , 1.       , 1.       , 1.       ,
       1.       , 1.       , 1.       , 1.       , 1.       , 1.       ,
       1.       , 1.       , 1.       , 1.       , 1.       , 1.       ,
       1.       , 1.       , 1.       , 1.       , 1.       , 1.       ,
       1.       , 1.       , 1.       , 1.       , 1.       , 1.       ,
       1.       , 1.       ], dtype=float32)

In [75]:
trt3[0][:50]

array([[0.997208],
       [0.997208],
       [0.997208],
       [0.997208],
       [0.997208],
       [0.997208],
       [0.997208],
       [0.997208],
       [0.997208],
       [0.997208],
       [0.997208],
       [0.997208],
       [0.997208],
       [0.996078],
       [0.996078],
       [0.996078],
       [0.996078],
       [0.996078],
       [0.996078],
       [1.      ],
       [1.      ],
       [1.      ],
       [1.      ],
       [1.      ],
       [1.      ],
       [1.      ],
       [1.      ],
       [1.      ],
       [1.      ],
       [1.      ],
       [1.      ],
       [1.      ],
       [1.      ],
       [1.      ],
       [1.      ],
       [1.      ],
       [1.      ],
       [1.      ],
       [1.      ],
       [1.      ],
       [1.      ],
       [1.      ],
       [1.      ],
       [1.      ],
       [1.      ],
       [1.      ],
       [1.      ],
       [1.      ],
       [1.      ],
       [1.      ]], dtype=float32)