## Imports

In [1]:
import cv2
import os
import numpy as np
from pathlib import Path
from matplotlib import pyplot as plt

## Debug Load Images Utility

In [2]:
folder = '/home/drevital/obstacles_classification_datasets/new_factory/obstacle_pairs_1'
test_folder = '/home/drevital/obstacles_classification_datasets/test_3'
imname = 'y1_1_252_.89_2021-07-27--16-25-03_.jpg'
im = cv2.imread(os.path.join(folder,imname))

In [3]:
im.shape

(84, 166, 3)

In [4]:
im[42][:10]

array([[110, 110, 110],
       [105, 105, 105],
       [109, 109, 109],
       [104, 104, 104],
       [105, 105, 105],
       [ 85,  85,  85],
       [ 52,  52,  52],
       [ 76,  76,  76],
       [223, 223, 223],
       [244, 244, 244]], dtype=uint8)

## Debug Generate Green:Green:0 Obstacle Images and Store Them

In [5]:
w = im.shape[1]

In [6]:
w

166

In [7]:
im1 = im[:,:w//2]

In [8]:
im1.shape

(84, 83, 3)

In [9]:
im1[42][:10]

array([[110, 110, 110],
       [105, 105, 105],
       [109, 109, 109],
       [104, 104, 104],
       [105, 105, 105],
       [ 85,  85,  85],
       [ 52,  52,  52],
       [ 76,  76,  76],
       [223, 223, 223],
       [244, 244, 244]], dtype=uint8)

In [10]:
im2 = im[:,w//2:]

In [11]:
im2.shape

(84, 83, 3)

In [12]:
im2[42][:10]

array([[118, 118, 118],
       [114, 114, 114],
       [107, 107, 107],
       [111, 111, 111],
       [105, 105, 105],
       [ 90,  90,  90],
       [ 83,  83,  83],
       [130, 130, 130],
       [231, 231, 231],
       [255, 255, 255]], dtype=uint8)

In [13]:
g_im1 = im1[:, :, 1]

In [14]:
g_im1.shape

(84, 83)

In [15]:
g_im1[42][:10]

array([110, 105, 109, 104, 105,  85,  52,  76, 223, 244], dtype=uint8)

In [16]:
g_im2 = im2[:, :, 1]

In [17]:
g_im2.shape

(84, 83)

In [18]:
g_im2[42][:10]

array([118, 114, 107, 111, 105,  90,  83, 130, 231, 255], dtype=uint8)

In [19]:
const = np.full((g_im1.shape[0]*g_im1.shape[1]), 127, dtype=np.uint8)

In [20]:
const.shape

(6972,)

In [21]:
const[:10]

array([127, 127, 127, 127, 127, 127, 127, 127, 127, 127], dtype=uint8)

In [22]:
const = const.reshape((g_im1.shape[0], g_im1.shape[1], 1))

In [23]:
const.shape

(84, 83, 1)

In [24]:
const[0][:10]

array([[127],
       [127],
       [127],
       [127],
       [127],
       [127],
       [127],
       [127],
       [127],
       [127]], dtype=uint8)

In [25]:
gg2ch = cv2.merge([g_im1, g_im2, const])

In [26]:
gg2ch.shape

(84, 83, 3)

In [27]:
gg2ch[42][:10]

array([[110, 118, 127],
       [105, 114, 127],
       [109, 107, 127],
       [104, 111, 127],
       [105, 105, 127],
       [ 85,  90, 127],
       [ 52,  83, 127],
       [ 76, 130, 127],
       [223, 231, 127],
       [244, 255, 127]], dtype=uint8)

In [28]:
prefix = imname.split('.')[-2]
png_name = prefix + '.png'
fpath = os.path.join(test_folder, png_name)
cv2.imwrite(fpath, gg2ch)

True

In [29]:
imtest = cv2.imread(os.path.join(test_folder, png_name))

In [30]:
imtest[42][:10]

array([[110, 118, 127],
       [105, 114, 127],
       [109, 107, 127],
       [104, 111, 127],
       [105, 105, 127],
       [ 85,  90, 127],
       [ 52,  83, 127],
       [ 76, 130, 127],
       [223, 231, 127],
       [244, 255, 127]], dtype=uint8)

## Load Images Utility

In [ ]:
def load_images_from_folder(folder):
    imnames = []
    images = []
    for imname in os.listdir(folder):
        im = cv2.imread(os.path.join(folder,imname))
        if im is not None:
            imnames.append(imname)
            images.append(im)
    return imnames, images

## Load & Process Loop

In [ ]:
obs_folder='/home/drevital/obstacles_classification_datasets/new_factory/obstacle_pairs_1'
obs_imnames, obs_images = load_images_from_folder(obs_folder)
no_obs_folder='/home/drevital/obstacles_classification_datasets/new_factory/no_obstacle_pairs_1'
no_obs_imnames, no_obs_images = load_images_from_folder(no_obs_folder)

## Generate Green:Green:0 Obstacle Images and Store Them

In [ ]:
gg2ch_folder = '/home/drevital/obstacles_classification_datasets/new_factory_gg_2_const/train/obstacle_1/'
Path(gg2ch_folder).mkdir(parents=True, exist_ok=True)

for i, imname in enumerate(obs_imnames):
    im = obs_images[i]
    w = im.shape[1]
    im1 = im[:,:w//2]
    im2 = im[:,w//2:]
    g_im1 = im1[:, :, 1]
    g_im2 = im2[:, :, 1]
    const = np.full((g_im1.shape[0]*g_im1.shape[1]), 127, dtype=np.uint8)
    const = const.reshape((g_im1.shape[0], g_im1.shape[1], 1))
    gg2ch = cv2.merge([g_im1, g_im2, const])
    fpath = os.path.join(gg2ch_folder, imname)
    cv2.imwrite(fpath, gg2ch)

## Generate Diff Non-Obstacle Images and Store Them

In [ ]:
gg2ch_folder = '/home/drevital/obstacles_classification_datasets/new_factory_gg_2_const/train/no_obstacle_1/'
Path(gg2ch_folder).mkdir(parents=True, exist_ok=True)

for i, imname in enumerate(no_obs_imnames):
    im = no_obs_images[i]
    w = im.shape[1]
    im1 = im[:,:w//2]
    im2 = im[:,w//2:]
    g_im1 = im1[:, :, 1]
    g_im2 = im2[:, :, 1]
    const = np.full((g_im1.shape[0]*g_im1.shape[1]), 127, dtype=np.uint8)
    const = const.reshape((g_im1.shape[0], g_im1.shape[1], 1))
    fpath = os.path.join(gg2ch_folder, imname)
    gg2ch = cv2.merge([g_im1, g_im2, const])
    cv2.imwrite(fpath, gg2ch)