In [28]:
import tensorflow as tf
import numpy as np

In [29]:
def custom_loss_1(y_true, y_pred):
    return tf.keras.metrics.categorical_crossentropy(y_true, y_pred)

In [30]:
def custom_loss_2(y_true, y_pred):
    yt_1_2 = y_true[:, 1:]
    yp_1_2 = y_pred[:, 1:]
    
    return tf.keras.metrics.categorical_crossentropy(y_true, y_pred)\
         + tf.keras.metrics.categorical_crossentropy(yt_1_2, yp_1_2)

In [31]:
y_true = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 0, 1]])
y_pred = np.array([[0.9, 0.1, 0.0], [0.1, 0.4, 0.5], [0.1, 0.5, 0.4], [0.1, 0.5, 0.4]])

In [32]:
custom_loss_1(y_true, y_pred)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0.10536052, 0.91629073, 0.91629073, 0.91629073])>

In [33]:
custom_loss_2(y_true, y_pred)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0.10536052, 1.72722095, 1.72722095, 1.72722095])>

In [22]:
yt_1_2 = y_true[:, 1:]

In [23]:
yt_1_2

array([[0, 0],
       [1, 0],
       [0, 1],
       [0, 1]])

In [25]:
yp_1_2 = y_pred[:, 1:]

In [26]:
yp_1_2

array([[0.1, 0. ],
       [0.4, 0.5],
       [0.5, 0.4],
       [0.5, 0.4]])

In [27]:
tf.keras.metrics.categorical_crossentropy(yt_1_2, yp_1_2)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0.        , 0.81093022, 0.81093022, 0.81093022])>